name: Cypress Tests

on:
  workflow_dispatch: # Define que o workflow será executado manualmente

jobs:
  api-tests:
    name: Run API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code # Faz o checkout do código do seu repositório
        uses: actions/checkout@v3

      - name: Setup Node.js # Configura o node para a versão especificada
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Dependencies # Instala as dependências do projeto
        run: |
          npm install

      - name: Run Cypress API Tests # Executa os testes de API
        run: |
          npm run cy:run:api